// // Copyright (c) 2025, inxeoz and contributors
// // For license information, please see license.txt

frappe.ui.form.on('MOM TABLE', {

    // meeting id function
    meeting_id: function(frm, cdt, cdn) {
        let row = locals[cdt][cdn];
        
        if (row.meeting_id) {
            // Check for duplicates
            let duplicate = false;
            frm.doc.mom_table.forEach(function(item) {
                if (item.name != cdn && item.meeting_id == row.meeting_id) {
                    duplicate = true;
                }
            });
            
            if (duplicate) {
                frappe.msgprint(__('This Meeting ID is already selected'));
                //frappe.model.set_value(cdt, cdn, 'meeting_id', '');
                

                 
                // Remove the duplicate row
                frm.doc.committee_member_table = frm.doc.committee_member_table.filter(function(item) {
                    return item.name !== cdn;
                });
                frm.refresh_field('committee_member_table');
                return;
            }
            
            // Fetch meeting details if no duplicate
            frappe.call({
                method: 'frappe.client.get_value',
                args: {
                    doctype: 'Minutes of Meeting',
                    filters: { name: row.meeting_id },
                    fieldname: ['agenda', 'type_of_meeting']
                },
                callback: function(r) {
                    if (r.message) {
                        // Set values in the row
                        frappe.model.set_value(cdt, cdn, {
                            'agenda': r.message.agenda || '',
                            'type_of_meeting': r.message.type_of_meeting || ''
                        });
                    }
                }
            });
        } else {
            // Clear fields
            frappe.model.set_value(cdt, cdn, {
                'agenda': '',
                'type_of_meeting': ''
            });
        }
    },
    
    // Trigger when a new row is added mom_table_add auto generated by frappe
    // convention is 
    // <child_table_name>_add: Triggered when a new row is added to the child table.
    // <child_table_name>_remove: Triggered when a row is removed from the child table.
    // <field_name>: Triggered when the value of the field is changed.
    
    mom_table_add: function(frm, cdt, cdn) {
        // Clear fields for new row
        let row = locals[cdt][cdn];
        row.agenda = '';
        row.type_of_meeting = '';
    }
});

frappe.ui.form.on('Committee Member Table', {

    // member id function
    member_id: function(frm, cdt, cdn) {
        let row = locals[cdt][cdn];
        
        if (row.member_id) {
            // Check for duplicates
            let duplicate = false;
            frm.doc.committee_member_table.forEach(function(item) {
                if (item.name != cdn && item.member_id == row.member_id) {
                    duplicate = true;
                }
            });
            
            if (duplicate) {
                frappe.msgprint(__('This Member is already in the committee'));
                //frappe.model.set_value(cdt, cdn, 'member_id', '');

                // Remove the duplicate row
                frm.doc.committee_member_table = frm.doc.committee_member_table.filter(function(item) {
                    return item.name !== cdn;
                });
                frm.refresh_field('committee_member_table');
                return;
            }
            
            // Fetch member details if no duplicate
            frappe.call({
                method: 'frappe.client.get_value',
                args: {
                    doctype: 'Member',
                    filters: { name: row.member_id },
                    fieldname: ['member_name', 'designation', 'role_in_committee']
                },
                callback: function(r) {
                    if (r.message) {
                        // Check for Chairman role
                        if (r.message.role_in_committee == "Chairman") {
                            // Count existing chairmen (excluding current row)
                            let chairman_count = 0;
                            frm.doc.committee_member_table.forEach(function(item) {
                                if (item.name != cdn && item.role_in_committee == "Chairman") {
                                    chairman_count++;
                                }
                            });
                            
                            if (chairman_count > 0) {
                                frappe.msgprint(__("Only One Chairman allowed"));
                                frappe.model.set_value(cdt, cdn, {
                                    'member_id': '',
                                    'member_name': '',
                                    'designation': '',
                                    'role_in_committee': ''
                                });
                                return;
                            }
                        }
                        
                        // Set values in the row
                        frappe.model.set_value(cdt, cdn, {
                            'member_name': r.message.member_name || '',
                            'designation': r.message.designation || '',
                            'role_in_committee': r.message.role_in_committee || '',
                        });
                    }
                }
            });
        } else {
            // Clear fields
            frappe.model.set_value(cdt, cdn, {
                'member_name': '',
                'designation': '',
                'role_in_committee': ''
            });
        }
    },
    
    committee_member_table_add: function(frm, cdt, cdn) {
        // Clear fields for new row
        let row = locals[cdt][cdn];
        row.member_name = '';
        row.designation = '';
        row.role_in_committee = '';
    },
    
    // Handle row removal to update chairman count
    committee_member_table_remove: function(frm, cdt, cdn) {
        frm.refresh_field('committee_member_table');
    }
});

frappe.ui.form.on("Bid Document", {

    onload: function(frm) {
        // Fetch data for existing rows when form loads
        if (frm.doc.mom_table) {
            frm.doc.mom_table.forEach(function(row) {
                if (row.meeting_id && (!row.agenda || !row.type_of_meeting)) {
                    // Trigger the meeting_id function for each row
                    frm.trigger('meeting_id', row.doctype, row.name);
                }
            });
        }

        if (frm.doc.committee_member_table) {
            frm.doc.committee_member_table.forEach(function(row) {
                if (row.member_id) {
                    frm.trigger('member_id', row.doctype, row.name);
                }
            });
        }
    },

    refresh(frm) {
        user = frappe.session.user;
        user_roles = frappe.user_roles;

        if (frm.doc.workflow_state === "Rejected" && user_roles.includes('Procurement Officer')) {
            frm.add_custom_button("Use as Template", function() {
                let fields = [
                    "bid_title",
                    "description__scope_of_work",
                    "bid_type",
                    "submission_start",
                    "submission_end"
                ];
                
                let field_data = {};
                fields.forEach(field => {
                    field_data[field] = frm.doc[field];
                });

                frappe.new_doc("Bid Document", field_data);
            });
        }
    }
});