// // Copyright (c) 2025, inxeoz and contributors
// // For license information, please see license.txt

frappe.ui.form.on('MOM TABLE', {

    // meeting id function
    meeting_id: function(frm, cdt, cdn) {
        let row = locals[cdt][cdn];
        
        if (row.meeting_id) {
            frappe.call({
                method: 'frappe.client.get_value',
                args: {
                    doctype: 'Minutes of Meeting',
                    filters: { name: row.meeting_id },
                    fieldname: ['agenda', 'type_of_meeting']
                },
                callback: function(r) {
                    if (r.message) {
                        // Set values in the row
                        frappe.model.set_value(cdt, cdn, {
                            'agenda': r.message.agenda || '',
                            'type_of_meeting': r.message.type_of_meeting || ''
                        });
                    }
                }
            });
        } else {
            // Clear fields
            frappe.model.set_value(cdt, cdn, {
                'agenda': '',
                'type_of_meeting': ''
            });
        }
    },
    
    // Trigger when a new row is added mom_table_add auto generated by frappe
    // convention is 
    // <child_table_name>_add: Triggered when a new row is added to the child table.
    // <child_table_name>_remove: Triggered when a row is removed from the child table.
    // <field_name>: Triggered when the value of the field is changed.

    mom_table_add: function(frm, cdt, cdn) {
        // Clear fields for new row
        let row = locals[cdt][cdn];
        row.agenda = '';
        row.type_of_meeting = '';
    }
});



frappe.ui.form.on('Committee Member Table', {

    // meeting id function
    member_id: function(frm, cdt, cdn) {
        let row = locals[cdt][cdn];
        
        if (row.member_id) {
            frappe.call({
                method: 'frappe.client.get_value',
                args: {
                    doctype: 'Member',
                    filters: { name: row.member_id },
                    fieldname: ['member_name', 'designation', 'role_in_committee']
                },
                callback: function(r) {

                    
                    if (r.message) {
                        
                        // Set values in the row
                        if ( r.message.role_in_committee == "Chairman" ){
                            //frappe.msgprint("Only One Chairman allowed")

                            frm._chairman_count  = (frm._chairman_count || 0) + 1

                            if (frm._chairman_count > 1) {
                                frappe.msgprint("Only One Chairman allowed")

                                frappe.model.set_value(cdt, cdn, {
                                    'member_name': r.message.member_name || '',
                                    'designation': r.message.designation || '',
                                    'role_in_committee' :  '',
                                });

                                
                                return //from here no updation
                            }
                        }
                        frappe.model.set_value(cdt, cdn, {
                            'member_name': r.message.member_name || '',
                            'designation': r.message.designation || '',
                            'role_in_committee' : r.message.role_in_committee || '',
                        });
                    }
                }
            });
        } else {
            // Clear fields
            frappe.model.set_value(cdt, cdn, {
                'member_name': '',
                'designation': '',
                'role_in_committee' : ''
            });
        }
    },
    
    // Trigger when a new row is added mom_table_add auto generated by frappe
    // convention is 
    // <child_table_name>_add: Triggered when a new row is added to the child table.
    // <child_table_name>_remove: Triggered when a row is removed from the child table.
    // <field_name>: Triggered when the value of the field is changed.

    committee_member_table_add: function(frm, cdt, cdn) {
        // Clear fields for new row
        let row = locals[cdt][cdn];
        row.member_name = '';
        row.designation = '';
    }
});


frappe.ui.form.on("Bid Document", {


    onload: function(frm) {
        // Fetch data for existing rows when form loads
        if (frm.doc.mom_table) {
            frm.doc.mom_table.forEach(function(row) {
                if (row.meeting_id && (!row.agenda || !row.type_of_meeting)) {
                    // Trigger the meeting_id function for each row
                    frm.trigger('meeting_id', row.doctype, row.name);
                }
            });
        }


        if (frm.doc.committee_member_table) {

            frm._chairman_count = 0;
            chairman_count  = 0
            frm.doc.committee_member_table.forEach(function(row) {
                if (row.member_id ) {
                    frm.trigger('member_id', row.doctype, row.name);
                }

               
            });
        }

    },

    refresh(frm) {
   
        user =frappe.session.user
        user_roles = frappe.user_roles
    

        if (frm.doc.workflow_state === "Rejected" && user_roles.includes('Procurement Officer') ) {
            frm.add_custom_button("Use as Template", function() {
                // Your logic to create bid form goes here

                   let fields = [
                    // "bid_document_status",
                    "bid_title",
                    "description__scope_of_work",
                    "bid_type",
                    "submission_start",
                    "submission_end"
                ];
                 // Create a data object for new_doc fields
                let field_data = {};
                fields.forEach(field => {
                    field_data[field] = frm.doc[field];
                });

                // Create the new document with these field values
                frappe.new_doc("Bid Document", field_data);
                
            });
        }

    }
});

