import frappe
from typing import List, Dict, Any

def get_merged_bid_workflow_states():
    """Returns merged workflow states configuration"""
    
    workflow_states = [
        {
            "no": 1,
            "id": "Draft",
            "state": "Draft",
            "workflow_state_name": "Draft",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "draft",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Primary",
            "icon": "file",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [ "Procurement Officer" ],
            "only_hide_to" : [ ]
        },
        {
            "no": 2,
            "id": "RQ Submitted For Approval",
            "state": "RQ Submitted For Approval", 
            "workflow_state_name": "RQ Submitted For Approval",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for MD Approval",
            "only_allow_edit_for": "Managing Director",
            "style": "Warning",
            "icon": "share",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : ["Procurement Officer" ]

        },
        {
            "no": 3,
            "id": "RQ Approved",
            "state": "RQ Approved",
            "workflow_state_name": "RQ Approved",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending to creation of BCCM",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Success",
            "icon": "check",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : ["Procurement Officer" ]
        },
        {
            "no": 4,
            "id": "BCCM Submitted For Approval",
            "state": "BCCM Submitted For Approval",
            "workflow_state_name": "BCCM Submitted For Approval",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for PD Approval",
            "only_allow_edit_for": "Project Director",
            "style": "Warning",
            "icon": "share",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [ "Project Director" ],
            "only_hide_to" : [ ]
            
        },
        {
            "no": 5,
            "id": "BCCM Verified By PD",
            "state": "BCCM Verified By PD",
            "workflow_state_name": "BCCM Verified By PD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for CGM Approval",
            "only_allow_edit_for": "Chief General Manager",
            "style": "Info",
            "icon": "user-check",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 6,
            "id": "BCCM Verified By CGM",
            "state": "BCCM Verified By CGM",
            "workflow_state_name": "BCCM Verified By CGM",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for MD Approval",
            "only_allow_edit_for": "Managing Director",
            "style": "Info",
            "icon": "user-check",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 7,
            "id": "BCCM Verified By MD",
            "state": "BCCM Verified By MD",
            "workflow_state_name": "BCCM Verified By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending to upload BCC Offline",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Success",
            "icon": "crown",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 8,
            "id": "UBO Submitted For Approval",
            "state": "UBO Submitted For Approval",
            "workflow_state_name": "UBO Submitted For Approval",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for CGM Approval",
            "only_allow_edit_for": "Chief General Manager",
            "style": "Warning",
            "icon": "share",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 9,
            "id": "UBO Verified By CGM",
            "state": "UBO Verified By CGM",
            "workflow_state_name": "UBO Verified By CGM",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for MD Approval",
            "only_allow_edit_for": "Managing Director",
            "style": "Info",
            "icon": "user-check",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 10,
            "id": "UBO Verified By MD",
            "state": "UBO Verified By MD",
            "workflow_state_name": "UBO Verified By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending to publish bid",
            "only_allow_edit_for": "Marketing Team",
            "style": "Success",
            "icon": "crown",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 11,
            "id": "Bid Published",
            "state": "Bid Published",
            "workflow_state_name": "Bid Published",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "waiting for Vendors query",
            "only_allow_edit_for": "System Manager",
            "style": "Success",
            "icon": "globe",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },

         
        {
            "no": 12,
            "id": "No Vendors Query",
            "state": "No Vendors Query",
            "workflow_state_name": "No Vendors Query",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending to upload TEC MOM",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Info",
            "icon": "question-circle",
            "is_optional_state": 1,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 13,
            "id": "TEC MOM Uploaded",
            "state": "TEC MOM Uploaded",
            "workflow_state_name": "TEC MOM Uploaded",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for CGM Approval",
            "only_allow_edit_for": "Chief General Manager",
            "style": "Warning",
            "icon": "upload",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 14,
            "id": "TEC MOM Verified By CGM",
            "state": "TEC MOM Verified By CGM",
            "workflow_state_name": "TEC MOM Verified By CGM",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for MD Approval",
            "only_allow_edit_for": "Managing Director",
            "style": "Info",
            "icon": "user-check",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 15,
            "id": "TEC MOM Verified By MD",
            "state": "TEC MOM Verified By MD",
            "workflow_state_name": "TEC MOM Verified By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending to upload FEC MOM",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Success",
            "icon": "crown",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 16,
            "id": "FEC MOM Uploaded",
            "state": "FEC MOM Uploaded",
            "workflow_state_name": "FEC MOM Uploaded",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for CGM Approval",
            "only_allow_edit_for": "Chief General Manager",
            "style": "Warning",
            "icon": "upload",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 17,
            "id": "FEC MOM Verified By CGM",
            "state": "FEC MOM Verified By CGM",
            "workflow_state_name": "FEC MOM Verified By CGM",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for MD Approval",
            "only_allow_edit_for": "Managing Director",
            "style": "Info",
            "icon": "user-check",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 18,
            "id": "FEC MOM Verified By MD",
            "state": "FEC MOM Verified By MD",
            "workflow_state_name": "FEC MOM Verified By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "Approved",
            "only_allow_edit_for": "System Manager",
            "style": "Success",
            "icon": "crown",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        },
        {
            "no": 19,
            "id": "Rejected",
            "state": "Rejected",
            "workflow_state_name": "Rejected",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "Rejected",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Danger",
            "icon": "x-circle",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to" : [  ],
            "only_hide_to" : [ ]
        }
    ]
    
    return workflow_states