import frappe
from typing import List, Dict, Any


def get_merged_bid_workflow_states() -> List[Dict[str, Any]]:
    """Returns merged workflow states configuration"""
    
    workflow_states = [
        {
            "no": 1,
            "id": "Draft",
            "state": "Draft",
            "workflow_state_name": "Draft",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "draft",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Primary",
            "icon": "file",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer"],
            "only_hide_to": []
        },
        {
            "no": 2,
            "id": "RQ Submitted For Approval",
            "state": "RQ Submitted For Approval",
            "workflow_state_name": "RQ Submitted For Approval",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for MD Approval",
            "only_allow_edit_for": "Managing Director",
            "style": "Warning",
            "icon": "share",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Managing Director"],
            "only_hide_to": []
        },
        {
            "no": 3,
            "id": "RQ Approved By MD",
            "state": "RQ Approved By MD",
            "workflow_state_name": "RQ Approved By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending to creation of BCCM",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Success",
            "icon": "check",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Managing Director"],
            "only_hide_to": []
        },
        {
            "no": 4,
            "id": "BCCM Submitted For Approval",
            "state": "BCCM Submitted For Approval",
            "workflow_state_name": "BCCM Submitted For Approval",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for PD Approval",
            "only_allow_edit_for": "Project Director",
            "style": "Warning",
            "icon": "share",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Project Director"],
            "only_hide_to": []
        },
        {
            "no": 5,
            "id": "BCCM Approved By PD",
            "state": "BCCM Approved By PD",
            "workflow_state_name": "BCCM Approved By PD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for CGM Approval",
            "only_allow_edit_for": "Chief General Manager",
            "style": "Info",
            "icon": "user-check",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Project Director", "Chief General Manager"],
            "only_hide_to": []
        },
        {
            "no": 6,
            "id": "BCCM Approved By CGM",
            "state": "BCCM Approved By CGM",
            "workflow_state_name": "BCCM Approved By CGM",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for MD Approval",
            "only_allow_edit_for": "Managing Director",
            "style": "Info",
            "icon": "user-check",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Chief General Manager", "Managing Director"],
            "only_hide_to": []
        },
        {
            "no": 7,
            "id": "BCCM Approved By MD",
            "state": "BCCM Approved By MD",
            "workflow_state_name": "BCCM Approved By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending to upload BCC Offline",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Success",
            "icon": "crown",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Managing Director"],
            "only_hide_to": []
        },
        {
            "no": 8,
            "id": "UBO Submitted For Approval",
            "state": "UBO Submitted For Approval",
            "workflow_state_name": "UBO Submitted For Approval",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for CGM Approval",
            "only_allow_edit_for": "Chief General Manager",
            "style": "Warning",
            "icon": "share",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Chief General Manager"],
            "only_hide_to": []
        },
        {
            "no": 9,
            "id": "UBO Approved By CGM",
            "state": "UBO Approved By CGM",
            "workflow_state_name": "UBO Approved By CGM",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for MD Approval",
            "only_allow_edit_for": "Managing Director",
            "style": "Info",
            "icon": "user-check",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Chief General Manager", "Managing Director"],
            "only_hide_to": []
        },
        {
            "no": 10,
            "id": "UBO Approved By MD",
            "state": "UBO Approved By MD",
            "workflow_state_name": "UBO Approved By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending to publish bid",
            "only_allow_edit_for": "Marketing Team",
            "style": "Success",
            "icon": "crown",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Managing Director", "Marketing Team"],
            "only_hide_to": []
        },
        {
            "no": 11,
            "id": "Bid Published",
            "state": "Bid Published",
            "workflow_state_name": "Bid Published",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "waiting for Vendors query",
            "only_allow_edit_for": "System Manager",
            "style": "Success",
            "icon": "globe",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": [],
            "only_hide_to": []
        },
        {
            "no": 12,
            "id": "No Vendors Query",
            "state": "No Vendors Query",
            "workflow_state_name": "No Vendors Query",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending to upload TEC MOM",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Info",
            "icon": "question-circle",
            "is_optional_state": 1,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Managing Director", "Marketing Team"],
            "only_hide_to": []
        },
        {
            "no": 13,
            "id": "TECMOM Uploaded",
            "state": "TECMOM Uploaded",
            "workflow_state_name": "TECMOM Uploaded",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for CGM Approval",
            "only_allow_edit_for": "Chief General Manager",
            "style": "Warning",
            "icon": "upload",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Chief General Manager"],
            "only_hide_to": []
        },
        {
            "no": 14,
            "id": "TECMOM Approved By CGM",
            "state": "TECMOM Approved By CGM",
            "workflow_state_name": "TECMOM Approved By CGM",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for MD Approval",
            "only_allow_edit_for": "Managing Director",
            "style": "Info",
            "icon": "user-check",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Chief General Manager", "Managing Director"],
            "only_hide_to": []
        },
        {
            "no": 15,
            "id": "TECMOM Approved By MD",
            "state": "TECMOM Approved By MD",
            "workflow_state_name": "TECMOM Approved By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending to upload FECMOM",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Success",
            "icon": "crown",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Managing Director"],
            "only_hide_to": []
        },
        {
            "no": 16,
            "id": "FECMOM Uploaded",
            "state": "FECMOM Uploaded",
            "workflow_state_name": "FECMOM Uploaded",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for CGM Approval",
            "only_allow_edit_for": "Chief General Manager",
            "style": "Warning",
            "icon": "upload",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Managing Director"],
            "only_hide_to": []
        },
        {
            "no": 17,
            "id": "FECMOM Approved By CGM",
            "state": "FECMOM Approved By CGM",
            "workflow_state_name": "FECMOM Approved By CGM",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "pending for MD Approval",
            "only_allow_edit_for": "Managing Director",
            "style": "Info",
            "icon": "user-check",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Chief General Manager", "Managing Director"],
            "only_hide_to": []
        },
        {
            "no": 18,
            "id": "FECMOM Approved By MD",
            "state": "FECMOM Approved By MD",
            "workflow_state_name": "FECMOM Approved By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "Approved",
            "only_allow_edit_for": "System Manager",
            "style": "Success",
            "icon": "crown",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": ["Procurement Officer", "Managing Director", "Marketing Team"],
            "only_hide_to": []
        },
        {
            "no": 19,
            "id": "Rejected",
            "state": "Rejected",
            "workflow_state_name": "Rejected",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "Rejected",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Danger",
            "icon": "x-circle",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": [],
            "only_hide_to": []
        },
        {
            "no": 20,
            "id": "RQ Rejected By MD",
            "state": "RQ Rejected By MD",
            "workflow_state_name": "RQ Rejected By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "RQ Rejected By MD",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Danger",
            "icon": "x-circle",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": [],
            "only_hide_to": []
        },
        {
            "no": 21,
            "id": "BCCM Rejected By PD",
            "state": "BCCM Rejected By PD",
            "workflow_state_name": "BCCM Rejected By PD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "BCCM Rejected By PD",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Danger",
            "icon": "x-circle",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": [],
            "only_hide_to": []
        },
        {
            "no": 22,
            "id": "BCCM Rejected By CGM",
            "state": "BCCM Rejected By CGM",
            "workflow_state_name": "BCCM Rejected By CGM",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "BCCM Rejected By CGM",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Danger",
            "icon": "x-circle",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": [],
            "only_hide_to": []
        },
        {
            "no": 23,
            "id": "BCCM Rejected By MD",
            "state": "BCCM Rejected By MD",
            "workflow_state_name": "BCCM Rejected By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "BCCM Rejected By MD",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Danger",
            "icon": "x-circle",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": [],
            "only_hide_to": []
        },
        {
            "no": 24,
            "id": "UBO Rejected By CGM",
            "state": "UBO Rejected By CGM",
            "workflow_state_name": "UBO Rejected By CGM",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "UBO Rejected By CGM",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Danger",
            "icon": "x-circle",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": [],
            "only_hide_to": []
        },
        {
            "no": 25,
            "id": "UBO Rejected By MD",
            "state": "UBO Rejected By MD",
            "workflow_state_name": "UBO Rejected By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "UBO Rejected By MD",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Danger",
            "icon": "x-circle",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": [],
            "only_hide_to": []
        },
        {
            "no": 26,
            "id": "TECMOM Rejected By CGM",
            "state": "TECMOM Rejected By CGM",
            "workflow_state_name": "TECMOM Rejected By CGM",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "TECMOM Rejected By CGM",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Danger",
            "icon": "x-circle",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": [],
            "only_hide_to": []
        },
        {
            "no": 27,
            "id": "TECMOM Rejected By MD",
            "state": "TECMOM Rejected By MD",
            "workflow_state_name": "TECMOM Rejected By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "TECMOM Rejected By MD",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Danger",
            "icon": "x-circle",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": [],
            "only_hide_to": []
        },
        {
            "no": 28,
            "id": "FECMOM Rejected By CGM",
            "state": "FECMOM Rejected By CGM",
            "workflow_state_name": "FECMOM Rejected By CGM",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "FECMOM Rejected By CGM",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Danger",
            "icon": "x-circle",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": [],
            "only_hide_to": []
        },
        {
            "no": 29,
            "id": "FECMOM Rejected By MD",
            "state": "FECMOM Rejected By MD",
            "workflow_state_name": "FECMOM Rejected By MD",
            "doc_status": 0,
            "update_field": "bid_document_status",
            "update_value": "FECMOM Rejected By MD",
            "only_allow_edit_for": "Procurement Officer",
            "style": "Danger",
            "icon": "x-circle",
            "is_optional_state": 0,
            "creation_date": "2024-01-01",
            "only_visible_to": [],
            "only_hide_to": []
        }
    ]
    
    return workflow_states
